package com.mixnmore.qbconnector.service;

import com.mixnmore.qbconnector.types.ArrayOfString;
import com.mixnmore.qbconnector.util.TypeFactory;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated
 * source version: 2.1
 *
 */
@WebService(name = "QBWebConnectorSvcSoap", targetNamespace = "http://developer.intuit.com/")
@XmlSeeAlso({TypeFactory.class})
public interface QBWebConnectorSvcSoap {

    @WebMethod(action = "http://developer.intuit.com/authenticate")
    @WebResult(name = "authenticateResult", targetNamespace = "http://developer.intuit.com/")
    @RequestWrapper(localName = "authenticate", targetNamespace = "http://developer.intuit.com/", className = "com.mixnmore.qbconnector.types.Authenticate")
    @ResponseWrapper(localName = "authenticateResponse", targetNamespace = "http://developer.intuit.com/", className = "com.mixnmore.qbconnector.types.AuthenticateResponse")
    public ArrayOfString authenticate(
            @WebParam(name = "strUserName", targetNamespace = "http://developer.intuit.com/") String strUserName,
            @WebParam(name = "strPassword", targetNamespace = "http://developer.intuit.com/") String strPassword);
    
    @WebMethod(action = "http://developer.intuit.com/sendRequestXML")
    @WebResult(name = "sendRequestXMLResult", targetNamespace = "http://developer.intuit.com/")
    @RequestWrapper(localName = "sendRequestXML", targetNamespace = "http://developer.intuit.com/", className = "com.mixnmore.qbconnector.types.SendRequestXML")
    @ResponseWrapper(localName = "sendRequestXMLResponse", targetNamespace = "http://developer.intuit.com/", className = "com.mixnmore.qbconnector.types.SendRequestXMLResponse")
    public String sendRequestXML(
            @WebParam(name = "ticket", targetNamespace = "http://developer.intuit.com/") String ticket,
            @WebParam(name = "strHCPResponse", targetNamespace = "http://developer.intuit.com/") String strHCPResponse,
            @WebParam(name = "strCompanyFileName", targetNamespace = "http://developer.intuit.com/") String strCompanyFileName,
            @WebParam(name = "qbXMLCountry", targetNamespace = "http://developer.intuit.com/") String qbXMLCountry,
            @WebParam(name = "qbXMLMajorVers", targetNamespace = "http://developer.intuit.com/") int qbXMLMajorVers,
            @WebParam(name = "qbXMLMinorVers", targetNamespace = "http://developer.intuit.com/") int qbXMLMinorVers);
    
    @WebMethod(action = "http://developer.intuit.com/receiveResponseXML")
    @WebResult(name = "receiveResponseXMLResult", targetNamespace = "http://developer.intuit.com/")
    @RequestWrapper(localName = "receiveResponseXML", targetNamespace = "http://developer.intuit.com/", className = "com.mixnmore.qbconnector.types.ReceiveResponseXML")
    @ResponseWrapper(localName = "receiveResponseXMLResponse", targetNamespace = "http://developer.intuit.com/", className = "com.mixnmore.qbconnector.types.ReceiveResponseXMLResponse")
    public int receiveResponseXML(
            @WebParam(name = "ticket", targetNamespace = "http://developer.intuit.com/") String ticket,
            @WebParam(name = "response", targetNamespace = "http://developer.intuit.com/") String response,
            @WebParam(name = "hresult", targetNamespace = "http://developer.intuit.com/") String hresult,
            @WebParam(name = "message", targetNamespace = "http://developer.intuit.com/") String message);
    
    @WebMethod(action = "http://developer.intuit.com/connectionError")
    @WebResult(name = "connectionErrorResult", targetNamespace = "http://developer.intuit.com/")
    @RequestWrapper(localName = "connectionError", targetNamespace = "http://developer.intuit.com/", className = "com.mixnmore.qbconnector.types.ConnectionError")
    @ResponseWrapper(localName = "connectionErrorResponse", targetNamespace = "http://developer.intuit.com/", className = "com.mixnmore.qbconnector.types.ConnectionErrorResponse")
    public String connectionError(
            @WebParam(name = "ticket", targetNamespace = "http://developer.intuit.com/") String ticket,
            @WebParam(name = "hresult", targetNamespace = "http://developer.intuit.com/") String hresult,
            @WebParam(name = "message", targetNamespace = "http://developer.intuit.com/") String message);
    
    @WebMethod(action = "http://developer.intuit.com/getLastError")
    @WebResult(name = "getLastErrorResult", targetNamespace = "http://developer.intuit.com/")
    @RequestWrapper(localName = "getLastError", targetNamespace = "http://developer.intuit.com/", className = "com.mixnmore.qbconnector.types.GetLastError")
    @ResponseWrapper(localName = "getLastErrorResponse", targetNamespace = "http://developer.intuit.com/", className = "com.mixnmore.qbconnector.types.GetLastErrorResponse")
    public String getLastError(
            @WebParam(name = "ticket", targetNamespace = "http://developer.intuit.com/") String ticket);
    
    @WebMethod(action = "http://developer.intuit.com/closeConnection")
    @WebResult(name = "closeConnectionResult", targetNamespace = "http://developer.intuit.com/")
    @RequestWrapper(localName = "closeConnection", targetNamespace = "http://developer.intuit.com/", className = "com.mixnmore.qbconnector.types.CloseConnection")
    @ResponseWrapper(localName = "closeConnectionResponse", targetNamespace = "http://developer.intuit.com/", className = "com.mixnmore.qbconnector.types.CloseConnectionResponse")
    public String closeConnection(
            @WebParam(name = "ticket", targetNamespace = "http://developer.intuit.com/") String ticket);

}